// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, fs, jade, mongoose, path, _;

  express = require('express');

  jade = require('jade');

  fs = require('fs');

  _ = require('underscore');

  mongoose = require('mongoose');

  path = require('path');

  mongoose.connect('localhost', 'test');

  app = express();

  app.use(express.bodyParser({
    keepExtensions: true,
    uploadDir: __dirname + '/static/uploads'
  }));

  app.use(express.cookieParser('secret'));

  app.use(express.methodOverride());

  app.use(express.cookieSession({
    cookie: {
      maxAge: 100000000
    }
  }));

  app.use(express["static"](__dirname + '/static'));

  app.set('views', 'views/');

  app.set('view engine', 'jade');

  app.set('view options', {
    layout: true
  });

  app.use(function(req, res, next) {
    app.locals.user = req.session.user;
    return next();
  });

  app.get('/', function(req, res) {
    return res.sendfile('index.html');
  });

  app.get('/index.html', function(req, res) {
    return res.sendfile('index.html');
  });

  app.get('/guide', function(req, res) {
    return res.render("guide.jade");
  });

  require('./routes/admin.js')(app);

  require('./routes/cart.js')(app);

  require('./routes/member.js')(app);

  require('./routes/products.js')(app);

  require('./routes/comment.js')(app);

  require('./routes/about.js')(app);

  app.listen(3000);

}).call(this);
