// Generated by CoffeeScript 1.4.0
(function() {
  var News;

  News = require('../models/news');

  module.exports = function(app) {
    app.get('/about', function(req, res) {
      return res.render('about.jade');
    });
    return app.get('/about/news', function(req, res) {
      return News.find({}, function(error, news) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.render('about_news.jade', {
          news: news
        });
      });
    });
  };

}).call(this);
