// Generated by CoffeeScript 1.4.0
(function() {
  var User;

  User = require('../models/user');

  module.exports = function(app) {
    return app.post('/address', function(req, res) {
      return '';
    });
  };

}).call(this);
