// Generated by CoffeeScript 1.4.0
(function() {
  var Product, mongoose, _;

  mongoose = require('mongoose');

  Product = require('../models/product.js');

  _ = require('underscore');

  module.exports = function(app) {
    app.get('/cart/add/:productid', function(req, res) {
      return Product.find({
        _id: req.params.productid
      }, function(err, products) {
        var p, prod, product, productid;
        product = products[0];
        productid = product._id.toString();
        if (req.session['cart'] === void 0) {
          req.session['cart'] = [
            {
              quantity: 1,
              product: product,
              id: productid
            }
          ];
        } else {
          p = (function() {
            var _i, _len, _ref, _results;
            _ref = req.session['cart'];
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              prod = _ref[_i];
              if (prod.id === productid) {
                _results.push(prod);
              }
            }
            return _results;
          })();
          if (p.length === 0) {
            req.session['cart'].push({
              quantity: 1,
              id: productid,
              product: product
            });
          } else {
            p[0].quantity++;
          }
        }
        return res.render('cart.jade', {
          cart: req.session['cart']
        });
      });
    });
    app.get('/cart/remove/:productid', function(req, res) {
      var newcart;
      console.log(req.params.productid);
      newcart = _.map(req.session['cart'], function(product) {
        if (product.id === req.params.productid) {
          product.quantity--;
        }
        if (product.quantity < 0) {
          product.quantity = 0;
        }
        return product;
      });
      req.session['cart'] = newcart;
      return res.render('cart.jade', {
        cart: req.session['cart']
      });
    });
    app.get('/cart/delete/:productid', function(req, res) {
      var item;
      req.session['cart'] = (function() {
        var _i, _len, _ref, _results;
        _ref = req.session['cart'];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (item.id !== req.params.productid) {
            _results.push(item);
          }
        }
        return _results;
      })();
      return res.redirect('/cart');
    });
    app.get('/cart', function(req, res) {
      return res.render('cart.jade', {
        cart: req.session['cart']
      });
    });
    app.get('/cart/checkout', function(req, res) {
      return res.render('cart_checkout.jade');
    });
    return app.post('/cart/confirm-order', function(req, res) {
      var order;
      order = Order({
        products: req.session['cart'],
        userId: req.session['user']._id,
        addressId: req.param("address"),
        status: 'paid',
        amount: _.reduce(req.session['cart'], function(sum, product) {
          return product.quantity * product.product.memberPrice + sum;
        }, 0)
      });
      return order.save(function(err) {
        return res.redirect('/member/orders');
      });
    });
  };

}).call(this);
