// Generated by CoffeeScript 1.4.0
(function() {
  var Comment;

  Comment = require('../models/comment');

  module.exports = function(app) {
    return app.post('/comment', function(req, res) {
      var comment;
      comment = Comment({
        name: req.body.name,
        email: req.body.email,
        phone: req.body.phone,
        enquiry: req.body.enquiry
      });
      return comment.save(function(error) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.redirect('/guide');
      });
    });
  };

}).call(this);
