// Generated by CoffeeScript 1.4.0
(function() {
  var IndexProduct, Product, debug, mongoose;

  mongoose = require('mongoose');

  Product = require('../models/product.js');

  IndexProduct = require('../models/index-product.js');

  debug = require('debug')('routes/products');

  module.exports = function(app) {
    app.get('/products', function(req, res) {
      debug('/products', 'Finding products');
      return Product.find({
        onDiscount: true
      }, function(discount_err, discount_products) {
        debug('/products', 'found some discount products');
        if (!discount_err) {
          return Product.find({
            onGroupon: true
          }, function(groupon_err, groupon_products) {
            debug('/products', 'found some groupon products');
            if (!groupon_err) {
              return res.render("products.jade", {
                discount_products: discount_products,
                groupon_products: groupon_products
              });
            } else {
              return res.render("error.jade", {
                error: groupon_err
              });
            }
          });
        } else {
          return res.render("error.jade", {
            error: discount_err
          });
        }
      });
    });
    app.get('/products/:kind', function(req, res) {
      return Product.find({
        kind: req.params.kind
      }, function(error, products) {
        if (error) {
          return res.json({
            error: error
          });
        }
        return res.render('products_kind.jade', {
          products: products
        });
      });
    });
    app.get('/products/:kind/:productid', function(req, res) {
      return res.render('products_product.jade');
    });
    return app.get('/index-products', function(req, res) {
      return IndexProduct.find({}, function(error, products) {
        return res.json(products);
      });
    });
  };

}).call(this);
