// Generated by CoffeeScript 1.4.0
(function() {
  var IndexProduct, Product, debug, mongoose;

  mongoose = require('mongoose');

  Product = require('../models/product.js');

  IndexProduct = require('../models/index-product.js');

  debug = require('debug')('routes/products');

  module.exports = function(app) {
    app.get('/products', function(req, res) {
      return Product.find({}, function(error, products) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.render('products.jade', {
          products: products
        });
      });
    });
    app.get('/products/:kind', function(req, res) {
      return Product.find({
        kind: req.params.kind
      }, function(error, products) {
        if (error) {
          return res.json({
            error: error
          });
        }
        return res.render('products_kind.jade', {
          products: products
        });
      });
    });
    app.get('/products/:kind/:id', function(req, res) {
      return Product.findOne({
        _id: req.params.id
      }, function(error, product) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.render('products_product.jade', {
          product: product
        });
      });
    });
    return app.get('/index-products', function(req, res) {
      return IndexProduct.find({}, function(error, products) {
        return res.json(products);
      });
    });
  };

}).call(this);
