// Generated by CoffeeScript 1.4.0
(function() {
  var About;

  About = require('../../models/about');

  module.exports = function(app) {
    app.get('/admin/about', function(req, res) {
      return About.findOne({}, function(error, about) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.render('admin_about.jade', {
          about: about != null ? about.about : void 0,
          active_index: 7
        });
      });
    });
    return app.post('/admin/about', function(req, res) {
      return About.remove({}, function(error) {
        var about;
        about = new About({
          about: req.body.about
        });
        return about.save(function(error) {
          return res.redirect('/admin/about');
        });
      });
    });
  };

}).call(this);
