// Generated by CoffeeScript 1.4.0
(function() {
  var Comment;

  Comment = require('../../models/comment');

  module.exports = function(app) {
    app.get('/admin/comments', function(req, res) {
      return res.render('admin_comment.jade', {
        active_index: 6
      });
    });
    app.get('/admin/list_comments', function(req, res) {
      return Comment.find({}, function(error, comments) {
        return res.json(comments);
      });
    });
    app.get('/admin/comment/delete/:commentid', function(req, res) {
      return Comment.remove({
        _id: req.params.commentid
      }, function(error) {
        return res.redirect('/admin/comments');
      });
    });
    app.get('/admin/about', function(req, res) {
      return About.findOne({}, function(error, about) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.render('admin_about.jade', {
          about: about != null ? about.about : void 0,
          active_index: 7
        });
      });
    });
    return app.post('/admin/about', function(req, res) {
      return About.remove({}, function(error) {
        var about;
        about = new About({
          about: req.body.about
        });
        return about.save(function(error) {
          return res.redirect('/admin/about');
        });
      });
    });
  };

}).call(this);
