// Generated by CoffeeScript 1.4.0
(function() {
  var ExpressFee;

  ExpressFee = require('../../models/express-fee');

  module.exports = function(app) {
    app.get('/admin/express-fee', function(req, res) {
      return res.render('admin_express.jade');
    });
    app.get('/admin/list_express_fee', function(req, res) {
      return ExpressFee.listFlatten(function(error, fees) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.json(fees);
      });
    });
    return app.post('/admin/update_fee', function(req, res) {
      var id, key, val;
      id = req.param('pk');
      key = req.param('name');
      val = req.param('value');
      return ExpressFee.updateFlatten(id, key, val, function(error) {
        if (error) {
          return res.status(500);
        }
        return res.json({
          'status': 'ok'
        });
      });
    });
  };

}).call(this);
