// Generated by CoffeeScript 1.4.0
(function() {
  var fs;

  fs = require('fs');

  module.exports = function(app) {
    app.get('/admin/', function(req, res) {
      return res.render('admin_index.jade');
    });
    return fs.readdir(__dirname, function(error, files) {
      var file, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if (file.match(/\.js$/) && file !== 'index.js') {
          _results.push(require("./" + file)(app));
        }
      }
      return _results;
    });
  };

}).call(this);
