// Generated by CoffeeScript 1.4.0
(function() {
  var User;

  User = require('../../models/user');

  module.exports = function(app) {
    app.get('/admin/list_member', function(req, res) {
      return User.listFlatten(function(error, users) {
        return res.json(users);
      });
    });
    app.get('/admin/member', function(req, res) {
      return res.render('admin_member.jade', {
        active_index: 1
      });
    });
    app.get('/admin/member/delete/:memberid', function(req, res) {
      return User.remove({
        _id: req.params.memberid
      }, function(error) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.redirect('/admin/member');
      });
    });
    return app.post('/admin/update_member', function(req, res) {
      var setval;
      setval = {};
      setval[req.param('name')] = req.param('value');
      return User.update({
        _id: req.param('pk')
      }, {
        $set: setval
      }, function(error) {
        if (error) {
          return res.json({
            error: error
          });
        }
        return res.json({
          'status': 'ok'
        });
      });
    });
  };

}).call(this);
