// Generated by CoffeeScript 1.4.0
(function() {
  var News;

  News = require('../../models/news');

  module.exports = function(app) {
    app.get('/admin/news', function(req, res) {
      return res.render('admin_news.jade', {
        active_index: 8
      });
    });
    app.get('/admin/news/list', function(req, res) {
      return News.find({}, function(error, news) {
        return res.json(news);
      });
    });
    app.get('/admin/news/:id/delete', function(req, res) {
      return News.remove({
        _id: req.params.id
      }, function(error) {
        return res.redirect('/admin/news');
      });
    });
    app.get('/admin/news/:id/edit', function(req, res) {
      return News.findOne({
        _id: req.params.id
      }, function(error, news) {
        return res.render('admin_news_edit.jade', {
          active_index: 8,
          news: news
        });
      });
    });
    app.post('/admin/news/:id/edit', function(req, res) {
      return News.update({
        _id: req.params.id
      }, {
        $set: {
          title: req.body.title,
          content: req.body.content
        }
      }, function(error) {
        return res.redirect("/admin/news/" + req.params.id + "/edit");
      });
    });
    app.get('/admin/news/new', function(req, res) {
      return res.render('admin_news_add.jade', {
        active_index: 8
      });
    });
    return app.post('/admin/news/new', function(req, res) {
      var news;
      news = new News({
        title: req.body.title,
        content: req.body.content
      });
      return news.save(function(error) {
        return res.redirect('/admin/news');
      });
    });
  };

}).call(this);
