// Generated by CoffeeScript 1.4.0
(function() {
  var Order;

  Order = require('../../models/order');

  module.exports = function(app) {
    app.get('/admin/orders', function(req, res) {
      return res.render('admin_orders.jade', {
        active_index: 4
      });
    });
    return app.get('/admin/list_orders', function(req, res) {
      return Order.find({}, function(error, orders) {
        return res.json(orders);
      });
    });
  };

}).call(this);
