// Generated by CoffeeScript 1.4.0
(function() {
  var Product;

  Product = require('../../models/product');

  module.exports = function(app) {
    app.post('/admin/add_product', function(req, res) {
      var product;
      product = new Product({
        name: req.param('product_name'),
        description: req.param('product_description'),
        price: req.param('product_price'),
        memberPrice: req.param('product_member_price'),
        unit: req.param('product_unit'),
        kind: req.param('product_kind'),
        onDiscount: req.param('product_on_discount') ? true : false,
        onGroupon: req.param('product_on_groupon') ? true : false,
        image: '/uploads/' + path.basename(req.files.product_image.path)
      });
      return product.save(function(error) {
        return res.redirect('/admin/product');
      });
    });
    app.get('/admin/product', function(req, res) {
      return res.render('admin_product.jade', {
        active_index: 2
      });
    });
    app.get('/admin/list_product', function(req, res) {
      return Product.find(function(err, products) {
        return res.json(products);
      });
    });
    app.get('/admin/delete_product/:proudctid', function(req, res) {
      return Product.remove({
        _id: req.params.proudctid
      }, function(error) {
        return res.redirect('/admin/product');
      });
    });
    app.post('/admin/update_product', function(req, res) {
      var key, setval, val;
      setval = {};
      key = req.param("name");
      val = req.param("value");
      if (key === 'onGroupon' || key === 'onDiscount') {
        val = val === '1' ? true : false;
      }
      setval[key] = val;
      return Product.update({
        _id: req.param('pk')
      }, {
        $set: setval
      }, function(err) {
        if (err) {
          res.statusCode = 500;
          return res.send("");
        } else {
          return res.send("ok");
        }
      });
    });
    app.get('/admin/product/:id/detail', function(req, res) {
      return Product.findOne({
        _id: req.params.id
      }, function(error, product) {
        if (error) {
          return res.render('error.jade', {
            eror: error
          });
        }
        return res.render('admin_product_detail.jade', {
          active_index: 2,
          product: product
        });
      });
    });
    return app.post('/admin/product/:id/detail', function(req, res) {
      return Product.update({
        _id: req.params.id
      }, {
        $set: {
          detail: req.body.detail
        }
      }, function(error) {
        if (error) {
          return res.render('error.jade', {
            error: error
          });
        }
        return res.redirect("/admin/product/" + req.params.id + "/detail");
      });
    });
  };

}).call(this);
