// Generated by CoffeeScript 1.4.0
(function() {
  var Scroller;

  Scroller = require('../../models/scroller');

  module.exports = function(app) {
    app.get('/admin/scroller', function(req, res) {
      return res.render('admin_scroller.jade', {
        active_index: 9
      });
    });
    app.get('/admin/scroller/list', function(req, res) {
      return Scroller.find({}, function(error, scrollers) {
        return res.json(scrollers);
      });
    });
    app.get('/admin/scroller/:id/delete', function(req, res) {
      return Scroller.remove({
        _id: req.params.id
      }, function(error) {
        return res.redirect('/admin/scroller');
      });
    });
    app.get('/admin/scroller/:id/edit', function(req, res) {
      return Scroller.findOne({
        _id: req.params.id
      }, function(error, scrollers) {
        return res.render('admin_scroller_edit.jade', {
          active_index: 9,
          scrollers: scrollers
        });
      });
    });
    app.post('/admin/scroller/:id/edit', function(req, res) {
      return News.update({
        _id: req.params.id
      }, {
        $set: {
          title: req.body.title,
          content: req.body.content
        }
      }, function(error) {
        return res.redirect("/admin/news/" + req.params.id + "/edit");
      });
    });
    app.get('/admin/scroller/new', function(req, res) {
      return res.render('admin_news_add.jade', {
        active_index: 8
      });
    });
    return app.post('/admin/scroller/new', function(req, res) {
      var news;
      news = new News({
        title: req.body.title,
        content: req.body.content
      });
      return news.save(function(error) {
        return res.redirect('/admin/news');
      });
    });
  };

}).call(this);
