// Generated by CoffeeScript 1.4.0
(function() {
  var Scroller, path;

  path = require('path');

  Scroller = require('../../models/scroller');

  module.exports = function(app) {
    app.get('/admin/scroller', function(req, res) {
      return res.render('admin_scroller.jade');
    });
    app.get('/admin/scroller/list', function(req, res) {
      return Scroller.find({}, function(error, scrollers) {
        return res.json(scrollers);
      });
    });
    app.get('/admin/scroller/:id/delete', function(req, res) {
      return Scroller.remove({
        _id: req.params.id
      }, function(error) {
        return res.redirect('/admin/scroller');
      });
    });
    app.get('/admin/scroller/:id/edit', function(req, res) {
      return Scroller.findOne({
        _id: req.params.id
      }, function(error, scrollers) {
        return res.render('admin_scroller_edit.jade', {
          scrollers: scrollers
        });
      });
    });
    app.post('/admin/scroller/:id/edit', function(req, res) {
      return Scroller.update({
        _id: req.params.id
      }, {
        $set: {
          title: req.body.title,
          content: req.body.content
        }
      }, function(error) {
        return res.redirect("/admin/news/" + req.params.id + "/edit");
      });
    });
    app.get('/admin/scroller/new', function(req, res) {
      return res.render('admin_news_add.jade');
    });
    return app.post('/admin/scroller/new', function(req, res) {
      var scroller;
      scroller = new Scroller({
        title: req.body.scroller_title,
        link: req.body.scroller_link,
        image: '/uploads/' + path.basename(req.files.scroller_image.path)
      });
      return scroller.save(function(error) {
        return res.redirect('/admin/scroller');
      });
    });
  };

}).call(this);
