// Generated by CoffeeScript 1.4.0
(function() {
  var About, aboutSchema, mongoose;

  mongoose = require('mongoose');

  aboutSchema = new mongoose.Schema({
    about: String
  });

  About = mongoose.model('About', aboutSchema);

  module.exports = About;

}).call(this);
