// Generated by CoffeeScript 1.4.0
(function() {
  var Comment, commentSchema, mongoose;

  mongoose = require('mongoose');

  commentSchema = new mongoose.Schema({
    name: String,
    email: String,
    phone: String,
    enquiry: String
  });

  Comment = mongoose.model('Comment', commentSchema);

  module.exports = Comment;

}).call(this);
