// Generated by CoffeeScript 1.4.0
(function() {
  var ExpressFee, expressFeeSchema, mongoose;

  mongoose = require('mongoose');

  expressFeeSchema = new mongoose.Schema({
    province: String,
    sfFee: {
      basicFee: {
        type: Number
      },
      basicWeight: {
        type: Number
      },
      extraFeeUnit: {
        type: Number
      },
      extraWeightUnit: {
        type: Number
      }
    },
    othersFee: {
      basicFee: {
        type: Number
      },
      basicWeight: {
        type: Number
      },
      extraFeeUnit: {
        type: Number
      },
      extraWeightUnit: {
        type: Number
      }
    }
  });

  expressFeeSchema.methods.calculateFee = function(type, weight) {
    var basicFee, basicWeight, extraFee, extraFeeUnit, extraWeightUnit, fee;
    fee = type === 'sf' ? this.sfFee : this.othersFee;
    basicWeight = fee.basicWeight;
    basicFee = fee.basicFee;
    extraFeeUnit = fee.extraFeeUnit;
    extraWeightUnit = fee.extraWeightUnit;
    if (weight <= basicWeight) {
      return basicFee;
    }
    extraFee = Math.ceil((weight - basicWeight) / extraWeightUnit) * extraFeeUnit;
    return basicFee + extraFee;
  };

  expressFeeSchema.methods.calculateSFFee = function(weight) {
    return this.calculateFee('sf', weight);
  };

  expressFeeSchema.methods.calculateOthersFee = function(weight) {
    return this.calculateFee('others', weight);
  };

  ExpressFee = mongoose.model('ExpressFee', expressFeeSchema);

  module.exports = ExpressFee;

}).call(this);
