// Generated by CoffeeScript 1.4.0
(function() {
  var expressFeeSchema, mongoose;

  mongoose = require('mongoose');

  expressFeeSchema = new mongoose.Schema({
    province: String,
    sfFee: Number,
    othersFee: Number,
    unit: {
      type: String,
      "default": 'kg'
    }
  });

  module.exports = mongoose.model('ExpressFee', expressFeeSchema);

}).call(this);
