// Generated by CoffeeScript 1.4.0
(function() {
  var indexProductSchema, mongoose;

  mongoose = require('mongoose');

  indexProductSchema = new mongoose.Schema({
    name: String,
    description: String,
    image: String,
    type: String,
    link: String
  });

  module.exports = mongoose.model('IndexProduct', indexProductSchema);

}).call(this);
