// Generated by CoffeeScript 1.4.0
(function() {
  var IndexProduct, indexProductSchema, mongoose;

  mongoose = require('mongoose');

  indexProductSchema = new mongoose.Schema({
    name: String,
    description: String,
    image: String,
    type: String,
    link: String
  });

  IndexProduct = mongoose.model('IndexProduct', indexProductSchema);

  module.exports = IndexProduct;

}).call(this);
