// Generated by CoffeeScript 1.4.0
(function() {
  var News, mongoose, newsSchema;

  mongoose = require('mongoose');

  newsSchema = new mongoose.Schema({
    title: String,
    content: String,
    time: {
      type: Date,
      "default": Date.now
    }
  });

  News = mongoose.model('News', newsSchema);

  module.exports = News;

}).call(this);
