// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose, productSchema;

  mongoose = require('mongoose');

  productSchema = new mongoose.Schema({
    name: String,
    description: String,
    price: String,
    memberPrice: Number,
    onDiscount: Boolean,
    onGroupon: Boolean,
    image: String,
    kind: String,
    unit: String
  });

  module.exports = mongoose.model('Product', productSchema);

}).call(this);
