// Generated by CoffeeScript 1.4.0
(function() {
  var addressSchema, mongoose, userSchema;

  mongoose = require('mongoose');

  addressSchema = new mongoose.Schema({
    name: String,
    province: String,
    city: String,
    address: String,
    phone: String,
    zipCode: String,
    deliveryMethod: String
  });

  userSchema = new mongoose.Schema({
    email: String,
    password: String,
    addresses: [addressSchema]
  });

  module.exports = mongoose.model('User', userSchema);

}).call(this);
